#!/bin/bash
# Command for running neovim

docker_image=thawk/spacevim

if [[ "$1" = /* ]]; then
    file_name="$(basename ${1})"
    dir_name="$(dirname ${1})"

    shift

    # Run the docker command
    docker run -it --rm -P -v "$dir_name":/src "${docker_image}" "$file_name" "$@"
else
    # Run the docker command
    docker run -it --rm -P -v "$(pwd)":/src "${docker_image}" "$@"
fi

