name: Trigger Homebrew Release
on:
  release:
    types: [released]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.HOMEBREW_TRIGGER_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/pwndbg/homebrew-tap/dispatches \
            -d '{"event_type":"pwndbg_release","client_payload":{"version":"${{ github.event.release.tag_name }}"}}'
