#DEFAULT_USER=$USER

POWERLEVEL9K_MODE="nerdfont-complete"

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=()
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS+=(os_icon)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS+=(dir)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS+=(virtualenv)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS+=(vcs)

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=(status)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=(root_indicator)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=(command_execution_time)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=(background_jobs)
[[ -n "${SSH_CLIENT}" ]] && POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=(context)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=(time)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=(ssh)

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

# prompt
local user_symbol="$"
if [[ $(print -P "%#") =~ "#" ]]; then
    user_symbol = "#"
fi

#POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="╭"
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%{%B%F{yellow}%K{blue}%} $user_symbol%{%b%f%k%F{blue}%} %{%f%}"
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="╰ %{%B%F{black}%K{blue}%} $user_symbol %{%b%f%k%F{blue}%} %{%f%}"
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="╰ $user_symbol "
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%{%K{black}%}\u256D\u2500%{%k%}"
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%{%K{black}%}\u2570\uf460 $user_symbol %{%F{black}%k%}%{%f%k%}"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%{%K{black}%}\u2570\uf460%{%F{black}%k%}%{%f%k%}"

# context
POWERLEVEL9K_CONTEXT_TEMPLATE="%n@`hostname -s` \uf109"
#POWERLEVEL9K_CONTEXT_TEMPLATE="\U1f4BB%n@`hostname -s`"

# time
#POWERLEVEL9K_TIME_FORMAT="%D{%F %T}"
POWERLEVEL9K_TIME_FORMAT="\uf017 %D{%H:%M:%S}"
POWERLEVEL9K_TIME_ICON=""
POWERLEVEL9K_TIME_BACKGROUND="cyan"
POWERLEVEL9K_TIME_FOREGROUND="black"

# status
POWERLEVEL9K_STATUS_OK=false

# vcs
POWERLEVEL9K_SHOW_CHANGESET=false
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6

POWERLEVEL9K_VCS_GIT_GITHUB_ICON=""
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=""
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=""
POWERLEVEL9K_VCS_GIT_ICON=""

# ssh
POWERLEVEL9K_SSH_BACKGROUND="blue"
POWERLEVEL9K_SSH_FOREGROUND="black"

# virtualenv
POWERLEVEL9K_VIRTUALENV_BACKGROUND="green"
POWERLEVEL9K_VIRTUALENV_FOREGROUND="black"
